### ISSUE TITLE
How to check a directory using allowed?

### ISSUE THREAD

**Issue by alexlee002** [robotdana/fast_ignore#12]
```ruby
include_rules = FastIgnore.new(root: Dir.pwd, relative:true, include_rules: ['/MyDir/*'])
include_rules.allowed?('MyDir/SubDir/', directory:true)

=> false
```

why?

**Comment by alexlee002** [comment]
```ruby
  def allowed?(path, directory: nil, content: nil)
    full_path = ::File.expand_path(path, @root)
    return false unless full_path.start_with?(@root)
    return false if directory.nil? ? @follow_symlinks_method.call(full_path).directory? : directory
```
why here return false if `path` is a directory?

**Comment by robotdana** [comment]
sorry somehow i missed this notification. 

if you do `git ls-files` you will not see any directories in output (thus people use files like .gitkeep). FastIgnore behaves the same way, it only gives files. because my idea of what counts as allowed  is based on being as close to what git ls-files does, and trying to match how gitignore behaves as close as possible, returning directories is wrong.

you could force FastIgnore to consider the path is not a directory but a file (using `allowed?(path, directory: false)`) and see how it survives the gitignore rules. it might run afoul of the result cache in lib/rule_set.rb, and it will be backward for .gitignore rules that end in `/`.

if you have suggestions for a what you're trying to do here, and maybe we end up with a directory mode that is more incompatible with git ls-files but has its own consistent logic. i'd need to rework the caching a bit, which will hopefully not affect performance too much in the gitignore compatible case

**Comment by robotdana** [comment]
i know It's been a year (pretty much exactly, huh) and i'm sorry it took this look, but you now can with version 0.17.0 and `allowed?(path, include_directories: true)`
