### ISSUE TITLE
.gitignore not respected while trying to run spellr

### ISSUE THREAD

**Issue by geoffevason** [robotdana/fast_ignore#13]
I was trying to run spellr on a project and it complained about a folder that I had in my global .gitignore file.

### Git Config (global)

```
> git config --global --list

user.email=#####
user.name=Geoff Evason
core.excludesfile=~/.gitignore
```

### ~/.gitignore

```
> cat ~/.gitignore 

.idea
```

### Spellr output

```
>  bundle exec spellr

.idea/vcs.xml:3:19 <component name="VcsDirectoryMappings">
.idea/vcs.xml:4:39 <mapping directory="$PROJECT_DIR$" vcs="Git" />
.idea/workspace.xml:4:81 <list default="true" id="###" name="Default Changelist" comment="" />
.idea/workspace.xml:7:39 <option name="HIGHLIGHT_NON_ACTIVE_CHANGELIST" value="false" />
.idea/workspace.xml:22:31 <component name="ProjectLevelVcsManager" settingsEditedManually="true" />
.idea/workspace.xml:33:61 <property name="node.js.selected.package.eslint" value="(autodetect)" />
...
```

**Comment by robotdana** [comment]
i don't actually use `git config` to get your git config because fast_ignore otherwise runs without executing git. i find the gitconfig file according to git's documentation of where it looks for files and use that.

there's either an issue with the way i read the config file, or an issue finding the config file to read.
would you be able to add your git config file and its path? (find the relevant one with `git config --show-origin core.excludesfile`) and also let me know the value of $XDG_CONFIG_HOME

thank you :)

(also i'm just rereading the documentation and realised i'm not reading any of these env variables https://git-scm.com/docs/git-config#_environment so that might be why, please let me know if you have any of these set)

**Comment by robotdana** [comment]
(also i'm not reading quoted strings correctly, or ignoring comments.

**Comment by robotdana** [comment]
i'm also not handling include and includeif directives

**Comment by G-Rath** [comment]
@robotdana 

> (also i'm not reading quoted strings correctly, or ignoring comments.

this line means you're at least ignoring comments properly now ay? https://github.com/robotdana/fast_ignore/blob/main/lib/fast_ignore/gitignore_rule_builder.rb#L172

**Comment by robotdana** [comment]
thank you for reminding me i'd been fixing this issue but hadn't quite finished.

this issue is about parsing the git config file to find the configure global gitignore file, that link parses comments in the gitignore file

**Comment by robotdana** [comment]
@geoffevason sorry it took a while, but i did gradually add an actual gitconfig file parser, and i believe 0.16.0 of fast_ignore should probably fix whatever reason the right gitignore file wasn't being found.

if you still have access to a computer with a similar git config & gitignore setup, then
`gem install fast_ignore:0.16.0 && ruby -rfast_ignore -e "puts FastIgnore.new(relative: true).include?('.idea')"` should be false, where 0.15.2 would've had it as true

feel free to reopen if its still broken in some way
